---
# Crash Course Python for Data Science - Intro to Python  
---
# 06 - Numpy
---



## STOP! BEFORE GOING ANY FURTHER...  

Remember, this exercises are open book, open neighbour, open everything! Try to do them on your own before looking at the solution samples.



### Import Numpy as Np

In [1]:
# Make sure you run this cell first
import numpy as np
print('NumPy imported!')

NumPy imported!


### Generate random numbers
Create a (5,3) Numpy array of random integer values between 0 and 100.

In [0]:
### YOUR CODE GOES HERE ###

In [2]:
#@title Double click here for a sample solution

x = np.random.randint(0,100, (5,3))
x

array([[ 7, 23, 18],
       [80, 18, 37],
       [60, 44, 50],
       [97, 27, 40],
       [29, 22, 29]])

### Array practice

In [3]:
# Return the first row:

### YOUR CODE GOES HERE ###
first_row = x[0, :]
print("First row:", first_row)


First row: [ 7 23 18]


In [4]:
#@title Double click here for a sample solution

# Return the first row:
x[0,]

array([ 7, 23, 18])

In [5]:
# Return last column

### YOUR CODE GOES HERE ###
last_column = x[:, -1]
print("Last column:", last_column)


Last column: [18 37 50 40 29]


In [6]:
#@title Double click here for a sample solution

# Return last column
x[:, -1]

array([18, 37, 50, 40, 29])

In [8]:
# Return the third column values from the 4th and 5th rows

### YOUR CODE GOES HERE ###
third_column_values = x[3:5, 2]
print(third_column_values)



[40 29]


In [7]:
#@title Double click here for a sample solution

# Return the third column values from the 4th and 5th rows
x[3:5,2]

array([40, 29])

In [9]:
# Multiply every value in the array by 2

### YOUR CODE GOES HERE ###
multiplied_array = x * 2
print(multiplied_array)


[[ 14  46  36]
 [160  36  74]
 [120  88 100]
 [194  54  80]
 [ 58  44  58]]


In [10]:
#@title Double click here for a sample solution

# Multiply every value in the array by 2
x*2

array([[ 14,  46,  36],
       [160,  36,  74],
       [120,  88, 100],
       [194,  54,  80],
       [ 58,  44,  58]])

In [11]:
# Divide every value by 3

### YOUR CODE GOES HERE ###
divide_array = x / 3
print(divide_array)

[[ 2.33333333  7.66666667  6.        ]
 [26.66666667  6.         12.33333333]
 [20.         14.66666667 16.66666667]
 [32.33333333  9.         13.33333333]
 [ 9.66666667  7.33333333  9.66666667]]


In [12]:
#@title Double click here for a sample solution

# Divide every value by 3
x/3

array([[ 2.33333333,  7.66666667,  6.        ],
       [26.66666667,  6.        , 12.33333333],
       [20.        , 14.66666667, 16.66666667],
       [32.33333333,  9.        , 13.33333333],
       [ 9.66666667,  7.33333333,  9.66666667]])

In [13]:
# Increase the values in the first row by 12

### YOUR CODE GOES HERE ###
x[0, :] += 12  
print(x)


[[19 35 30]
 [80 18 37]
 [60 44 50]
 [97 27 40]
 [29 22 29]]


In [14]:
#@title Double click here for a sample solution

# Increase the values in the first row by 12
x[0,] = x[0,] + 12
x

array([[31, 47, 42],
       [80, 18, 37],
       [60, 44, 50],
       [97, 27, 40],
       [29, 22, 29]])

In [15]:
# Calculate the mean of the first column

### YOUR CODE GOES HERE ###
mean_first_column = x[:, 0].mean()
print(mean_first_column)


59.4


In [16]:
#@title Double click here for a sample solution

# Calculate the mean of the first column
x[:,0].mean()

np.float64(59.4)

In [17]:
# Calculate the median of the array after removing the 2 smallest values in the array

### YOUR CODE GOES HERE ###

x1 = np.delete(x, x.argmin())  
x1 = np.delete(x1, x1.argmin())
median_array = np.median(x1)
print(median_array)


42.0


In [19]:
#@title Double click here for a sample solution

# Calculate the median of the array after removing the 2 smallest values in the array
x1 = np.delete(x, x.argmin())
x1 = np.delete(x1, x1.argmin())
np.median(x1)


np.float64(42.0)

In [20]:
# Calculate the standard deviation of the first 3 rows

### YOUR CODE GOES HERE ###

std_first_3 = np.std(x[:3, :]) 
print(std_first_3)


16.5872180449024


In [21]:
#@title Double click here for a sample solution

# Calculate the standard deviation of the first 3 rows
np.std(x[:3],)

np.float64(16.5872180449024)

In [22]:
# Return values in the second column greater than 25

### YOUR CODE GOES HERE ###
greater_than = x[:, 1][x[:, 1] > 25]  
print(greater_than)


[47 44 27]


In [23]:
#@title Double click here for a sample solution

# Return values in the second column greater than 25
print("Values bigger than 25 on the second column =", x[:,1][x[:,1]>25])

Values bigger than 25 on the second column = [47 44 27]


In [26]:
# Return values in the array under 40

### YOUR CODE GOES HERE ###
array_under_40 = x[x<40]
print(array_under_40)

[31 18 37 27 29 22 29]


In [25]:
#@title Double click here for a sample solution

# Return values in the array under 40
print("Values under 40 in array =", x[x<40])

Values under 40 in array = [31 18 37 27 29 22 29]
